[versions]
activity = "1.9.3"
appcompat = "1.7.0"
coil = "2.2.2"
compose = "1.7.5"
composeNavigation = "2.8.4"
coroutines = "1.9.0"
datastore = "1.1.1"
documentfile = "1.1.0-alpha01"
hilt = "2.52"
hiltNavigation = "1.2.0"
immutableCollections = "0.3.7"
junit = "4.13.2"
jupiter = "5.11.2"
kotlin = "2.0.21"
kotlinxSerialization = "1.7.3"
kotlinxSerializationConverter = "0.8.0"
lifecycle = "2.8.7"
material3 = "1.3.1"
material3Adaptive = "1.1.0-alpha07"
mockk = "1.13.12"
opto = "1.1.0"
retrofit = "2.11.0"
room = "2.6.1"
viewmodel = "2.8.7"
timber = "5.0.1"
vico = "1.13.0-alpha.9"

androidPlugin = "8.7.2"
kspPlugin = "2.0.21-1.0.28"

[libraries]
activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose-material3-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "material3Adaptive" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
compose-navigation-material = { module = "androidx.compose.material:material-navigation", version = "1.7.0-beta01" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
hilt-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }
immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "immutableCollections" }
junit = { module = "junit:junit", version.ref = "junit" }
jupiter = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlinxSerializationConverter" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
opto-core = { module = "com.github.patrykandpatrick.opto:core", version.ref = "opto" }
opto-domain = { module = "com.github.patrykandpatrick.opto:domain", version.ref = "opto" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
safeArgs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "composeNavigation" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
vico = { module = "com.patrykandpatrick.vico:compose-m3", version.ref = "vico" }
viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewmodel" }

[bundles]
kotlin = ["kotlin-stdlib", "kotlin-coroutines"]
hilt = ["hilt-android", "hilt-navigation"]
opto = ["opto-core", "opto-domain"]
ui = ["coil", "compose-ui", "compose-ui-preview", "compose-material3", "compose-navigation", "vico", "immutable-collections", "compose-navigation-material", "compose-material3-adaptive"]
testing = ["junit", "jupiter", "kotlin-test", "kotlin-coroutines-test"]

[plugins]
application = { id = "com.android.application", version.ref = "androidPlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinXSerialization = { id = "kotlinx-serialization" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
library = { id = "com.android.library", version.ref = "androidPlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
