name: Build debug APK
on:
    push:
jobs:
    build_debug_apk:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3.3.0
                with:
                    java-version: 17
                    distribution: adopt
            -   run: |
                    chmod +x gradlew
                    ./gradlew assembleDebug
            -   uses: actions/upload-artifact@v3.1.0
                with:
                    name: Debug APK
                    path: app/build/outputs/apk/debug/**.apk
