name: Run Detekt
on:
    push:
jobs:
    run_detekt:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3.3.0
                with:
                    java-version: 17
                    distribution: adopt
            -   run: |
                    chmod +x gradlew
                    ./gradlew detekt
